name = "09wizardguy's Personal Modpack"
author = "09wizardguy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0282d847d97d33940ae8a5f0024c04ae89b6f0124d1b576012828217863671db"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.173"

[options]
acceptable-game-versions = ["1.21.1"]
