name = "Personal Create6 Modpack"
author = "09wizardguy"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13e212dc3002b713a547af71348d6fae6737dc6574ccffd263f9504e32e9a4e2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.197"

[options]
acceptable-game-versions = ["1.21.1"]
